name: "Build on Darwin"

on:
  # Build on push
  push:
    branches:
      - master

  # Build on internal pull requests
  pull_request:

  # Allow to trigger for external PRs
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
    - run: nix build .#default -L
    - run: nix build .#neovim -L
